use std::path::Path;

use specta_typescript::Typescript;
use tauri::Runtime;
use tauri_specta::{collect_commands, collect_events};

use crate::{commands, events::AppEvent};

/// Where the generated TypeScript bindings are committed.
pub const BINDINGS_PATH: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../ui/src/api/generated/bindings.ts"
);

/// Every command and event the frontend can reach.
#[must_use]
pub fn specta_builder<R: Runtime>() -> tauri_specta::Builder<R> {
    tauri_specta::Builder::<R>::new()
        .commands(collect_commands![
            commands::conversations::conversations_list,
            commands::conversations::conversations_latest_by_character,
            commands::conversations::conversations_latest_by_group,
            commands::conversations::conversation_open,
            commands::conversations::conversation_branches,
            commands::conversations::conversation_branch_fork,
            commands::conversations::conversation_branch_rename,
            commands::conversations::conversation_branch_select,
            commands::conversations::conversation_branch_delete,
            commands::conversations::conversation_duplicate,
            commands::conversations::conversation_branch_to_character_from_message,
            commands::conversations::conversation_branch_to_character,
            commands::conversations::conversation_branch_direct_to_character,
            commands::conversations::conversation_branch_direct_to_group,
            commands::conversations::conversation_messages,
            commands::conversations::message_edit,
            commands::conversations::message_delete,
            commands::conversations::messages_delete_after,
            commands::conversations::memory_rewind_retry,
            commands::conversations::message_pin,
            commands::conversations::message_candidate_select,
            commands::conversations::message_scene_select,
            commands::conversations::message_revisions,
            commands::conversations::message_candidates,
            commands::conversations::conversation_search,
            commands::conversations::conversation_pinned_messages,
            commands::conversations::conversation_message_count,
            commands::conversations::conversation_messages_around,
            commands::conversations::conversation_send,
            commands::conversations::conversation_regenerate,
            commands::conversations::conversation_continue,
            commands::conversations::conversation_retry,
            commands::conversations::conversation_add_user_message,
            commands::conversations::generation_cancel,
            commands::conversations::conversation_help_me_reply,
            commands::conversations::message_scene_image_approve,
            commands::conversations::message_scene_image_dismiss,
            commands::conversations::message_scene_image_generate,
            commands::conversations::message_scene_prompt_generate,
            commands::conversations::message_prompt_snapshot,
            commands::conversations::conversation_speaker_selection_preview,
            commands::conversations::conversation_participation_stats,
            commands::conversations::message_companion_effect,
            commands::conversations::conversation_launch_direct,
            commands::conversations::conversation_launch_group,
            commands::conversations::conversation_settings_get,
            commands::conversations::conversation_settings_update,
            commands::conversations::conversation_rename,
            commands::conversations::conversation_archive,
            commands::conversations::conversation_restore,
            commands::conversations::conversation_delete,
            commands::conversations::conversation_participant_add,
            commands::conversations::conversation_participant_update,
            commands::characters::characters_list,
            commands::prompts::prompts_list,
            commands::prompts::prompt_placeholders,
            commands::prompts::prompt_validate,
            commands::prompts::prompt_get,
            commands::prompts::prompt_create,
            commands::prompts::prompt_update,
            commands::prompts::prompt_delete,
            commands::prompts::prompt_builtin_reset,
            commands::prompts::prompt_app_default_set,
            commands::prompts::prompt_preview,
            commands::prompts::default_character_rules,
            commands::lorebooks::lorebooks_list,
            commands::lorebooks::lorebook_get,
            commands::lorebooks::lorebook_create,
            commands::lorebooks::lorebook_update_metadata,
            commands::lorebooks::lorebook_entries_mutate,
            commands::lorebooks::lorebook_archive,
            commands::lorebooks::lorebook_restore,
            commands::lorebooks::lorebook_delete,
            commands::lorebooks::tokens_count,
            commands::lorebooks::lorebook_trigger_preview,
            commands::lorebooks::lorebook_entry_draft,
            commands::lorebooks::lorebook_keywords_draft,
            commands::lorebooks::lorebook_project_create,
            commands::lorebooks::lorebook_project_get,
            commands::lorebooks::lorebook_projects_list,
            commands::lorebooks::lorebook_project_plan,
            commands::lorebooks::lorebook_project_outline_update,
            commands::lorebooks::lorebook_project_outline_approve,
            commands::lorebooks::lorebook_project_draft_update,
            commands::lorebooks::lorebook_project_draft_set_approved,
            commands::lorebooks::lorebook_project_coherence_apply,
            commands::lorebooks::lorebook_project_cancel,
            commands::lorebooks::lorebook_generator_defaults,
            commands::lorebooks::lorebook_project_draft_next,
            commands::lorebooks::lorebook_project_refine,
            commands::lorebooks::lorebook_project_coherence,
            commands::lorebooks::lorebook_project_commit,
            commands::jobs::jobs_list,
            commands::jobs::job_get,
            commands::jobs::job_cancel,
            commands::jobs::job_watch,
            commands::files::files_inspect,
            commands::files::assets_ingest,
            commands::app::app_status,
            commands::app::app_ui_state_update,
            commands::app::purge_notices_list,
            commands::app::purge_notice_dismiss,
            commands::local_models::llama_devices,
            commands::local_models::llama_context_info,
            commands::local_models::llama_chat_template,
            commands::local_models::llama_unload,
            commands::local_models::local_models_list,
            commands::local_models::local_model_delete,
            commands::local_models::local_model_adopt,
            commands::local_models::local_models_dir_get,
            commands::local_models::local_models_dir_set,
            commands::local_models::local_file_runnability,
            commands::image::image_generate,
            commands::image::image_upscale,
            commands::image::image_capabilities,
            commands::image::playground_history_list,
            commands::image::playground_history_delete,
            commands::image::sd_catalog,
            commands::image::sd_runtime_releases,
            commands::image::sd_runtime_install,
            commands::image::sd_runtime_inventory,
            commands::image::sd_runtime_switch,
            commands::image::sd_runtime_delete,
            commands::image::sd_model_install,
            commands::image::sd_models_installed,
            commands::image::sd_model_uninstall,
            commands::image::sd_model_repair,
            commands::image::sd_runnability,
            commands::image::sd_bundle_runnability,
            commands::image::sd_compute_policy_get,
            commands::image::sd_compute_policy_save,
            commands::image::sd_detect_model_file,
            commands::image::sd_disk_usage,
            commands::image::sd_component_library,
            commands::image::sd_upscalers_list,
            commands::image::sd_upscalers_install,
            commands::image::sd_upscalers_remove,
            commands::image::loras_list,
            commands::image::loras_import,
            commands::image::loras_delete,
            commands::image::loras_update_keywords,
            commands::image::lora_keywords_discover,
            commands::image::hf_image_bundle_profiles,
            commands::image::hf_image_bundle_search,
            commands::image::hf_image_bundle_files,
            commands::image::hf_image_bundle_install,
            commands::image::hf_image_bundle_retry,
            commands::image::hf_image_bundle_retry_registration,
            commands::image::image_models_downloaded,
            commands::image::civitai_search,
            commands::image::civitai_model,
            commands::image::civitai_auth_status,
            commands::image::civitai_auth_save,
            commands::image::civitai_auth_clear,
            commands::image::civitai_lora_download,
            commands::image::avatar_prompt,
            commands::image::avatar_gradient,
            commands::image::image_design_reference,
            commands::hugging_face::hf_search,
            commands::hugging_face::hf_model_files,
            commands::hugging_face::hf_readme,
            commands::hugging_face::hf_author,
            commands::hugging_face::hf_avatars,
            commands::hugging_face::hf_runnability,
            commands::hugging_face::hf_recommendation,
            commands::hugging_face::hf_download,
            commands::hugging_face::hf_auth_status,
            commands::hugging_face::hf_auth_save,
            commands::hugging_face::hf_auth_clear,
            commands::memory::memory_get,
            commands::memory::memory_add,
            commands::memory::memory_update,
            commands::memory::memory_delete,
            commands::memory::memory_pin,
            commands::memory::memory_set_temperature,
            commands::memory::memory_summary_update,
            commands::memory::memory_trigger,
            commands::memory::memory_retry,
            commands::memory::memory_skip,
            commands::memory::memory_cycles,
            commands::memory::memory_cycle_revert,
            commands::memory::memory_error_dismiss,
            commands::companion::companion_soul_get,
            commands::companion::companion_soul_growth_clear,
            commands::companion::companion_soul_growth_remove,
            commands::companion::companion_soul_growth_lock,
            commands::companion::companion_soul_writer_run,
            commands::companion::companion_notes_list,
            commands::companion::companion_notes_upsert,
            commands::companion::companion_notes_delete,
            commands::companion::companion_notes_active_preview,
            commands::memory_models::embedding_install,
            commands::memory_models::companion_emotion_install,
            commands::memory_models::embedding_status,
            commands::memory_models::embedding_choose,
            commands::memory_models::embedding_remove,
            commands::memory_models::embedding_compare,
            commands::memory_models::embedding_unload,
            commands::memory_models::companion_emotion_status,
            commands::memory_models::companion_emotion_remove,
            commands::speech::kokoro_inventory,
            commands::speech::kokoro_variants,
            commands::speech::kokoro_voices_installed,
            commands::speech::kokoro_voices_available,
            commands::speech::kokoro_install_model,
            commands::speech::kokoro_install_voices,
            commands::speech::kokoro_uninstall_model,
            commands::speech::kokoro_uninstall_voice,
            commands::speech::kokoro_blend,
            commands::speech::kokoro_phonemize,
            commands::speech::kokoro_tokenize_preview,
            commands::speech::audio_providers_list,
            commands::speech::audio_provider_update,
            commands::speech::audio_provider_delete,
            commands::speech::user_voices_list,
            commands::speech::user_voice_update,
            commands::speech::user_voice_delete,
            commands::speech::asr_learning_export,
            commands::speech::audio_provider_create,
            commands::speech::user_voice_create,
            commands::speech::asr_vocabulary_save,
            commands::speech::asr_correction_save,
            commands::speech::asr_suggestion_approve,
            commands::speech::asr_suggestion_ignore,
            commands::speech::asr_voice_example_save,
            commands::speech::asr_learning_import,
            commands::speech::asr_vocabulary_list,
            commands::speech::asr_corrections_list,
            commands::speech::asr_ignored_suggestions_list,
            commands::speech::asr_voice_examples_list,
            commands::speech::asr_voice_example_suggest,
            commands::speech::asr_vocabulary_delete,
            commands::speech::asr_correction_delete,
            commands::speech::asr_voice_example_delete,
            commands::speech::asr_suggestions,
            commands::speech::audio_provider_verify,
            commands::speech::audio_provider_credential_status,
            commands::speech::audio_provider_api_key_rotate,
            commands::speech::audio_provider_voices,
            commands::speech::audio_provider_voices_search,
            commands::speech::voice_design_preview,
            commands::speech::voice_design_create,
            commands::speech::audio_provider_voices_refresh,
            commands::speech::tts_models,
            commands::speech::tts_voice_design_models,
            commands::speech::tts_cache_stats,
            commands::speech::tts_cache_clear,
            commands::speech::tts_synthesize,
            commands::speech::message_speak,
            commands::speech::whisper_catalog,
            commands::speech::whisper_models_list,
            commands::speech::whisper_download,
            commands::speech::whisper_delete,
            commands::speech::whisper_preload,
            commands::speech::whisper_clear_cache,
            commands::speech::whisper_dictation_model_set,
            commands::speech::transcribe_file,
            commands::speech::dictation_start,
            commands::speech::dictation_stop,
            commands::speech::dictation_cancel,
            commands::ollama::ollama_models_list,
            commands::ollama::ollama_model_delete,
            commands::ollama::ollama_pull,
        ])
        .events(collect_events![AppEvent])
}

/// Writes the TypeScript bindings to `path`, ending in exactly one newline.
pub fn export_bindings(path: &Path) -> Result<(), Box<dyn std::error::Error>> {
    specta_builder::<tauri::Wry>().export(Typescript::default(), path)?;
    let text = std::fs::read_to_string(path)?;
    std::fs::write(path, format!("{}\n", text.trim_end()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn committed_bindings_are_current() {
        let directory =
            std::env::temp_dir().join(format!("lettuce-tauri-bindings-{}", std::process::id()));
        std::fs::create_dir_all(&directory).expect("temporary directory");
        let generated = directory.join("bindings.ts");
        export_bindings(&generated).expect("export bindings");
        let generated_text = std::fs::read_to_string(&generated).expect("generated bindings");
        std::fs::remove_dir_all(&directory).expect("remove temporary directory");
        let committed = std::fs::read_to_string(BINDINGS_PATH).unwrap_or_default();
        assert!(
            generated_text == committed,
            "apps/ui/src/api/generated/bindings.ts is stale; run `cargo run -p lettuce-tauri --bin export-bindings`"
        );
    }
}
