[package]
name = "lettuce-database"
readme = "README.md"
description = "SQLite schema and domain repository adapters."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
lettuce-characters.workspace = true
lettuce-media.workspace = true
lettuce-models.workspace = true
lettuce-settings.workspace = true
lettuce-types.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true
