[package]
name = "lettuce-contracts"
readme = "README.md"
description = "Versioned IPC contracts and generated frontend boundary."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
lettuce-types.workspace = true
serde.workspace = true
